name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake gcc-13 g++-13

    - name: Create build directory
      run: mkdir build-debug && cd build-debug

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: make

    - name: Run tests
      run: ctest --output-on-failure
